// Code generated by sqlc. DO NOT EDIT.
// source: channel.sql

package db

import (
	"context"
)

const GetChannel = `-- name: GetChannel :one
SELECT id, is_active, created_on, modified_on, uuid, channel_type, "name", address, country, claim_code, secret, last_seen, device, os, alert_email, config, schemes, "role", bod, tps, created_by_id, modified_by_id, org_id, parent_id
FROM public.channels_channel
WHERE uuid=$1
`

func (q *Queries) GetChannel(ctx context.Context, uuid string) (ChannelsChannel, error) {
	row := q.db.QueryRow(ctx, GetChannel, uuid)
	var i ChannelsChannel
	err := row.Scan(
		&i.ID,
		&i.IsActive,
		&i.CreatedOn,
		&i.ModifiedOn,
		&i.Uuid,
		&i.ChannelType,
		&i.Name,
		&i.Address,
		&i.Country,
		&i.ClaimCode,
		&i.Secret,
		&i.LastSeen,
		&i.Device,
		&i.Os,
		&i.AlertEmail,
		&i.Config,
		&i.Schemes,
		&i.Role,
		&i.Bod,
		&i.Tps,
		&i.CreatedByID,
		&i.ModifiedByID,
		&i.OrgID,
		&i.ParentID,
	)
	return i, err
}
