// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type ChannelsChannel struct {
	ID           int32          `json:"id,omitempty"`
	IsActive     bool           `json:"is_active,omitempty"`
	CreatedOn    time.Time      `json:"created_on,omitempty"`
	ModifiedOn   time.Time      `json:"modified_on,omitempty"`
	Uuid         string         `json:"uuid,omitempty"`
	ChannelType  string         `json:"channel_type,omitempty"`
	Name         string 				`json:"name,omitempty"`
	Address      string 				`json:"address,omitempty"`
	Country      string 				`json:"country,omitempty"`
	ClaimCode    string 				`json:"claim_code,omitempty"`
	Secret       string 				`json:"secret,omitempty"`
	LastSeen     time.Time      `json:"last_seen,omitempty"`
	Device       string 				`json:"device,omitempty"`
	Os           string 				`json:"os,omitempty"`
	AlertEmail   string 				`json:"alert_email,omitempty"`
	Config       string 				`json:"config,omitempty"`
	Schemes      interface{}    `json:"schemes,omitempty"`
	Role         string         `json:"role,omitempty"`
	Bod          string 				`json:"bod,omitempty"`
	Tps          int32  				`json:"tps,omitempty"`
	CreatedByID  int32          `json:"created_by_id,omitempty"`
	ModifiedByID int32          `json:"modified_by_id,omitempty"`
	OrgID        int32  				`json:"org_id,omitempty"`
	ParentID     int32  				`json:"parent_id,omitempty"`
}

type ChannelsChannellog struct {
	ID             int64          `json:"id,omitempty"`
	Description    string         `json:"description,omitempty"`
	IsError        bool           `json:"is_error,omitempty"`
	Url            string 				`json:"url,omitempty"`
	Method         string 				`json:"method,omitempty"`
	Request        string 				`json:"request,omitempty"`
	Response       string 				`json:"response,omitempty"`
	ResponseStatus int32  				`json:"response_status,omitempty"`
	CreatedOn      time.Time      `json:"created_on,omitempty"`
	RequestTime    int32  				`json:"request_time,omitempty"`
	ChannelID      int32          `json:"channel_id,omitempty"`
	ConnectionID   int32  				`json:"connection_id,omitempty"`
	MsgID          int64  				`json:"msg_id,omitempty"`
}
