// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
	"time"
)

type ChannelsChannel struct {
	ID           int32
	IsActive     bool
	CreatedOn    time.Time
	ModifiedOn   time.Time
	Uuid         string
	ChannelType  string
	Name         sql.NullString
	Address      sql.NullString
	Country      sql.NullString
	ClaimCode    sql.NullString
	Secret       sql.NullString
	LastSeen     time.Time
	Device       sql.NullString
	Os           sql.NullString
	AlertEmail   sql.NullString
	Config       sql.NullString
	Schemes      interface{}
	Role         string
	Bod          sql.NullString
	Tps          sql.NullInt32
	CreatedByID  int32
	ModifiedByID int32
	OrgID        sql.NullInt32
	ParentID     sql.NullInt32
}

type ChannelsChannellog struct {
	ID             int64
	Description    string
	IsError        bool
	Url            sql.NullString
	Method         sql.NullString
	Request        sql.NullString
	Response       sql.NullString
	ResponseStatus sql.NullInt32
	CreatedOn      time.Time
	RequestTime    sql.NullInt32
	ChannelID      int32
	ConnectionID   sql.NullInt32
	MsgID          sql.NullInt64
}
